# Generated by Django 4.2 on 2023-04-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='options',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
