# Generated by Django 4.2 on 2023-04-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0016_remove_question_writer_category_question_category'),
        ('students', '0006_remove_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Question.question'),
        ),
    ]
