# Generated by Django 4.2 on 2023-04-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0016_remove_question_writer_category_question_category'),
        ('students', '0007_alter_student_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Question.question'),
            preserve_default=False,
        ),
    ]
