# Generated by Django 4.2 on 2023-04-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='options',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='questions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
