# Generated by Django 4.2 on 2023-04-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_options_alter_student_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='questions',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
