# Generated by Django 4.2 on 2023-04-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_category_alter_student_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
    ]
