# Generated by Django 4.2 on 2023-07-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_enteremail_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnterEmail',
        ),
    ]
