# Generated by Django 4.2 on 2023-07-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0013_delete_enteremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('question_text', models.TextField(max_length=1000)),
                ('session_id', models.CharField(editable=False, max_length=200)),
            ],
        ),
    ]
