# Generated by Django 4.2 on 2023-04-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_questioner',
            field=models.BooleanField(default=False),
        ),
    ]
