# Generated by Django 4.2 on 2023-04-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_questioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='final_score',
            field=models.IntegerField(default=0),
        ),
    ]
