# Generated by Django 4.2 on 2023-04-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_final_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='final_score',
        ),
    ]
