# Generated by Django 4.2 on 2023-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_remove_question_options_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
