# Generated by Django 4.2 on 2023-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0003_alter_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ManyToManyField(to='Question.question'),
        ),
    ]
