# Generated by Django 4.2 on 2023-04-11 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Question', '0005_remove_option_question_option_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.ManyToManyField(to='Question.option'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.RemoveField(
            model_name='question',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.ManyToManyField(to='Question.score'),
        ),
        migrations.AddField(
            model_name='question',
            name='writer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
