# Generated by Django 4.2 on 2023-04-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0010_remove_question_options_remove_question_scores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ManyToManyField(to='Question.question'),
        ),
    ]
