# Generated by Django 4.2 on 2023-04-13 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Question', '0012_remove_option_question_option_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Question.option'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='question',
            name='writer',
        ),
        migrations.AddField(
            model_name='question',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
