# Generated by Django 4.2 on 2023-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0013_remove_option_question_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(to='Question.option'),
        ),
    ]
