# Generated by Django 4.2 on 2023-04-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0017_alter_option_question_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='selected_answer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
