# Generated by Django 4.2 on 2023-04-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0022_alter_category_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
