# Generated by Django 4.2 on 2023-04-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0025_question_question_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_list',
        ),
    ]
