# Generated by Django 4.2 on 2023-04-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0026_remove_question_question_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='final_score',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
