# Generated by Django 4.2 on 2023-05-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0027_question_final_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('?',)},
        ),
    ]
