# Generated by Django 4.2 on 2023-05-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0028_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
