# Generated by Django 4.2 on 2023-05-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0031_category_writer_alter_option_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
