# Generated by Django 4.2 on 2023-05-16 14:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0032_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('counter', django.db.models.manager.Manager()),
            ],
        ),
    ]
