# Generated by Django 4.2 on 2023-05-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0033_alter_question_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, editable=False, max_length=300, null=True)),
                ('answer_score', models.IntegerField(blank=True, editable=False, null=True)),
                ('final_score', models.IntegerField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='final_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='selected_answer',
        ),
    ]
