# Generated by Django 4.2 on 2023-05-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0034_answer_remove_question_answer_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.TextField(blank=True, editable=False, max_length=1000, null=True),
        ),
    ]
