# Generated by Django 4.2 on 2023-05-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0035_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, editable=False, max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to='Question.question'),
        ),
    ]
