# Generated by Django 4.2 on 2023-05-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_enteremail_delete_student'),
        ('Question', '0036_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.enteremail'),
            preserve_default=False,
        ),
    ]
