# Generated by Django 4.2 on 2023-05-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0037_answer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='email',
        ),
    ]
