# Generated by Django 4.2 on 2023-05-22 14:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0040_alter_category_category_name_alter_category_writer_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('sum_importance', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='option',
            managers=[
                ('max_score', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='importance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_score',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='final_score',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
