# Generated by Django 4.2 on 2023-06-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0041_alter_category_managers_alter_option_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='final_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='selected_answer',
        ),
        migrations.AlterField(
            model_name='category',
            name='importance',
            field=models.IntegerField(),
        ),
    ]
